### ISSUE TITLE
error - react scripts command not found.

### ISSUE THREAD

**Issue by SATYAM1548** [brittanyjoiner15/eui-event-template#107]
while working in local environment  I got one bug after running yarn start dev.
error stated react scripts not found

**Comment by bpvcode** [comment]
Hello @SATYAM1548 ,

I think, **but I'm not sure**, this could be related to the scripts declared in `package.json` file. As you will see in the next screenshot, there is no `yar start dev` declared in the scripts. But if you run only `yarn start` everything should run well because that script is declared in the file:

![package_json_scripts](https://user-images.githubusercontent.com/66181027/195567130-0534ac4f-7d4c-420d-a11f-7bb9b9313a5d.png)

If what I'm saying is correct, I think that we have 2 ways to resolve this issue. Or we change the script in `package.json` file, or we change the documentation in order to be accurate for people to understand and run the application locally with no problems.

What do you think @brittanyjoiner15 ?

**Comment by SATYAM1548** [comment]
@brittanyjoiner15 
hello!
I think @bpvcode is right we have two ways to resolve this issue.

**Comment by brittanyjoiner15** [comment]
@bpvcode thank you for digging into this! I really appreciate that. and @SATYAM1548 for reporting it! My recommendation is that we update the readme and it should say `yarn start` and not `yarn started dev`. @SATYAM1548 since you identified the bug, would you like to create a quick PR for that change?

**Comment by SATYAM1548** [comment]
@brittanyjoiner15 thanks for giving me this opportunity.
Yes, I would like to create a quick PR for that change.
can u label this issue as a hactoberfest issue

**Comment by brittanyjoiner15** [comment]
@SATYAM1548 added! also, it shouldnt be required since there's a topic in the repo for `hacktoberfest`, but i understand wanting to be double sure it counts, so i added it!

**Comment by SATYAM1548** [comment]
@brittanyjoiner15 thanks!

**Comment by m1ga** [comment]
just a quick info @brittanyjoiner15: 
no need for the label on the ticket, nor the `hacktoberfest-accepted` label on the PR itself. You've tagged the whole repo with `hacktoberfest` - that is enough :+1: 
Keep up the good work :heart:

**Comment by SATYAM1548** [comment]
@brittanyjoiner15 
thanks. this was my first open source contribution. Thankyou so much

**Comment by brittanyjoiner15** [comment]
@m1ga yeah thanks for confirming it's not needed! I assumed it wasn't but added that all to be sure. WIll save me some time to not have to worry about that anymore haha

and congrats @SATYAM1548 appreciate your help!!
