### ISSUE TITLE
Minor UI fixes

### ISSUE THREAD

**Issue by adsingh14** [brittanyjoiner15/eui-event-template#121]
On both live/local website:

1. Logo changes on switching theme
 
![image](https://user-images.githubusercontent.com/35252877/198669909-02a5048c-2d06-4ec6-81bd-d3a0a4da826d.png)
![image](https://user-images.githubusercontent.com/35252877/198669993-e699e4c5-cf31-4ec3-a919-a7145e032e01.png)

2. Full width container for navbar will look better
![image](https://user-images.githubusercontent.com/35252877/198672508-8ae052ef-c743-4e8f-a1f5-e2d0f5a7622b.png)

On local server:

1. `<svg>` icons are not visible.

![image](https://user-images.githubusercontent.com/35252877/198652375-661a3aba-9b9c-49b3-8ba4-a0851475d764.png)
![image](https://user-images.githubusercontent.com/35252877/198652627-c62dd290-13d2-49b2-b0a7-ef700b6dcf96.png)

2. Button flicker on toggle

https://user-images.githubusercontent.com/35252877/198667609-e881a25b-0fe8-405a-abd4-7dada2f070e2.mp4

---

I will contribute after discussion and getting assigned.

**Comment by brittanyjoiner15** [comment]
@adsingh14 i would love if you can fix these! Those are all great points, here are some additional details for you that may help. 

1. I am not too worried about this one, i know it's a different logo, but it's pretty subtle so im okay with it! But if you want to propose a light and dark version that is fine with me!
2. Agree on the full width navbar - that would be great, especially since our footer is full width
3. on the local server - the reason that the icons aren't showing is a very strange bug that was introduced in Eui with the version i started with, and it's since been fixed but i havent' upgraded Eui. I have another [issue out to do that](https://github.com/brittanyjoiner15/eui-event-template/issues/70), but it will probably be quite a bit of work. Feel free to skip over this one, if you'd like, or if you do want to do this, I can assign you that issue and you can do it in a separate PR!
4. The button flicker - i would LOVE if you can fix this! I thought we had it fixed before, but i think it might have jumped back in at some point.

**Comment by adsingh14** [comment]
Fourth point occurs only on local server, maybe that's connected with third point. Both 3rd and 4th points are working on live website.

I'm figuring the structure to fix the second one. The first one is optional as you said, my priority is only the second point.

**Comment by adsingh14** [comment]
Fourth point occurs only on local server, maybe that's connected with third point. Both 3rd and 4th points are working on live website.

@brittanyjoiner15 I'm figuring the structure to fix the second one*. The first one is optional as you said, my priority is only the second point. FAQs and Home page content is in **container** unlike the rest of three pages. I think it's good to put all content in container. What's your view on this ?

**Comment by adsingh14** [comment]
Fourth point occurs only on local server, maybe that's connected with third point. Both 3rd and 4th points are working on live website.

I'm figuring the structure and CSS. The first one is optional; my priority is only the second point. FAQs and Home page content is in container unlike the rest of three pages. Any thoughts on this ?

**Comment by brittanyjoiner15** [comment]
@adsingh14 ah right if it's only on local server, then yes it might have something to do with the 3rd point. 

agree on priority is the second point, and first point is optional!

As far as FAQs and Home page - that's a good catch. Maybe we should make that full page too rather than container so i matches other pages. What do you think?

**Comment by brittanyjoiner15** [comment]
@adsingh14 closing this out since we resolved the navbar, but if you want to make a separate issue for the full page on then FAQand home, go ahead and do that and ill assign to you!

**Comment by adsingh14** [comment]
@brittanyjoiner15 
> As far as FAQs and Home page - that's a good catch. Maybe we should make that full page too rather than container so i matches other pages. What do you think?

I think FAQs page doesn't need to be changed except a minor change. It looks better in center. Yes, I'm working on home page offline and checking EUI docs. 

-- 

Just curious, isn't this project covers 'hacktoberfest 2022'?

**Comment by brittanyjoiner15** [comment]
@adsingh14 sounds good, and yes it does!

**Comment by adsingh14** [comment]
> sounds good, and yes it does!

I was asking because there's no label on either issue or my commit.

**Comment by brittanyjoiner15** [comment]
@adsingh14 yep since the project has the topic `hacktoberfest` it's not need on every issue
