### ISSUE TITLE
[Improvement suggestion] As a user, I can click the navbar brand logo img and text to navigate back to the home page

### ISSUE THREAD

**Issue by AloyBranCheung** [brittanyjoiner15/eui-event-template#65]
Hi @brittanyjoiner15,

I'm new to open-source contributions and hoping to participate in my first hackathon. 

As the title suggest, I would like to propose a very simple improvement to UX to the navigation feature of your website based on what I am seeing on the production sample link. This feature would involve user feedback (i.e. a cursor change when hovering the navbar brand), in hopes of improving UX. 

Implementation Proposal: 
I am thinking of  adding `cursor: pointer` in the CSS and also making clicking the text navigate back to the homepage (in addition to the already implemented logo img). 

I havn't taken a look at the codebase yet but I would probably use react-dom or just using an `<a>` tag. 

Please let me know what you think about this and if it would be possible as contribution for hacktoberfest.

**Comment by brittanyjoiner15** [comment]
@AloyBranCheung welcome to open source contribution!! Thank you so much for your suggestion, and we are actually halfway there already - we did get the logo changed so that it redirects to the home page, but you make a good point about the site title as well!

If you'd like to work on that, that would be great! Please use the routing that we have set up already (you can mimic what was done with the logo, so it should be easy). Please make sure not to change any of the styles of the title. For instance, we don't want it to look like a link and be underlined or anything, just would like it to be clickable and behave similarly to the logo!

Let me know if that makes sense or if you need any help!

**Comment by AloyBranCheung** [comment]
Hi @brittanyjoiner15, thanks for the reply. I'm just writing to let you know I've received your assignment. I'll get cracking at orientating and tackling this once I find some time sometime this week. Is that ok?

**Comment by AloyBranCheung** [comment]
@brittanyjoiner15 I'm not sure how to make you a reviewer on my forked repo, but here's the URL to my pull request [https://github.com/AloyBranCheung/hacktoberEUI](url).

**Comment by brittanyjoiner15** [comment]
@AloyBranCheung yes that would be great, but please comment in here every couple of days letting me know your progress in here, because if i don't hear from you after a couple days, I will need to reassign. 

And that link actually goes to issues on my branch. I don't see any pull requests from you as they should be showing up over here: https://github.com/brittanyjoiner15/eui-event-template/pulls

Have you made changes to the code? Or just forked the repo?

**Comment by AloyBranCheung** [comment]
Can you let me know if I did it correctly? I first clicked 'use template' and I guess that forked the repo to me. Then I cloned my forked repo, made changes to the code and pushed my branch to my forked repo and now there's a pull request that I havn't merged yet because I wanted to add you as a reviewer. What have I done wrong?

**Comment by brittanyjoiner15** [comment]
Can you post a screenshot of the pull request? Specifically the top where it shows which branches it's comparing?

**Comment by AloyBranCheung** [comment]
![image](https://user-images.githubusercontent.com/104483060/193588084-5a4b84e8-ff70-4fcc-aece-c0959aed414b.png)

**Comment by brittanyjoiner15** [comment]
@AloyBranCheung so i believe that is on your repo - if you look at the URL, does it say `/brittanyjoiner/eui-event-template` or does it say `/aloybrancheung/somereponame` because if it's the latter, then you'll need to merge that to main on your fork and then request to merge that to the `brittanyjoiner15` repo.

So, one thing to note - you said you clicked `use template` and i think that behaves a little differently than a fork, i think it might be just copying the repo to your area, and not necessarily connecting it with the original repo. 

If you aren't seeing any options for creating a pull request with brittanyjoiner15/eui-event-template, then you might want to try again to actually fork the repo and not select `use template`

**Comment by brittanyjoiner15** [comment]
Check out this video I made showing how to fork and create a PR:

How to create a pull request with no coding required!
https://youtu.be/j1MUcVQn40g

**Comment by AloyBranCheung** [comment]
Hey, thanks so much for the help. The URL said `/aloybran/cheung/reponame` instead as you mentioned. I was following the instructions in your readme file so may we can change 'use template' to the fork button unless I read/understood it wrong. So I just forked the repo and copy/pasted the changes I made and it seems like it worked!

However, I can't find the cogwheel to add you as a reviewer.  I'll take a look at the video.

**Comment by brittanyjoiner15** [comment]
@AloyBranCheung yes! confirming i saw your PR opened in the right place and you'reg good to go! Im about to get on a plane but will take a look at it this afternoon!

And yeah - i probably need to update the PR template because i think folks can't actually add me as a reviewer. 

And re: the instructions in the readme, if you want to "use" the template, ie, you want to create your own site for an event then you will want to use the template option but if you want to contribute, then you'll need to fork it. I will create an issue for updating that to make it more clear - thanks for the feedback!

**Comment by AloyBranCheung** [comment]
Thanks for the clarification, that makes more sense maybe it's just because I'm a newbie in open-source haha. Have a safe trip, looking forward to your feedback.

**Comment by brittanyjoiner15** [comment]
@AloyBranCheung hahah no worries - i want to be as clear as possible so if it's not clear to you then it's not clear! So i will definitely update and clarify the difference between using and contributing and which process to take!
