### ISSUE TITLE
Translate key text in app to French

### ISSUE THREAD

**Issue by brittanyjoiner15** [brittanyjoiner15/eui-event-template#77]
After we have a i18n available, then we'll want to be able to translate key parts of the app. If you speak French and would feel comfortable translating the key text, that would be great!

This is what we need translated: 

* tab titles
  * `Event Details`
  * `Speakers`
  * `Talks`
  * `Recordings`
  * `FAQs/Frequently Asked Questions`
* Calendar Button text: `Save the {date} session`
* Second button text:
  * `Sign up for updates`
  * `Join the slack group`
* Button on talks page text:  `Show times in EDT` and `Show times in Local`

**Comment by bpvcode** [comment]
Hi there, can you assign this issue to me?
I want to work on this. And this should be probably my first contribution to Hacktoberfest (first time here ehehe) :)
Thank you

**Comment by brittanyjoiner15** [comment]
@bpvcode awesome! welcome! I see you are from Portugal - do you have any profiles or work that shows you know French? Would love a french speaker to take this issue since simply using Google Translate isn't always accurate. If you do speak French, that's great! But would just love to see some work that shows that!

**Comment by OjashKush** [comment]
can you assign this?

**Comment by bpvcode** [comment]
Hello @brittanyjoiner15  ,

Yes, I'm happy to say that I'm Portuguese :)
However, I work daily with French people, both colleagues, and clients. And this kind of translation doesn't seem to be much difficult btw.
I'm working as a backend developer on a French website that allows users to ship different packages around France. (I can't share the code because is on a private repo inside my company GitLab instance, once this is a client project).
I suggest I do a PR and you do a review on this, if you think is not good enough in terms of translation you reassign this issue to anyone who speaks French natively. What do you think?

Thank you :)

**Comment by brittanyjoiner15** [comment]
@bpvcode that's good enough for me! I'll assign to you now!

**Comment by brittanyjoiner15** [comment]
@OjashKush sorry, bruno asked about this first so I'll be assigning to him.

**Comment by bpvcode** [comment]
Hello, @brittanyjoiner15 I already did the PR for you to review.

I can't assign you as a `reviewer`, nor assign me as `assignee`. So I comment on the description of the PR. If it was just me that was a noob, please tell me how can i do this when I create a PR, that way in the next PR I will do it :)

I add the french translations as we talked, and I did small fixes as well, all explained in the PR description.

Hope you like it :)

If you need some changes please just tell me.

Thank you!
